# Introduction to numpy, pandas, and matplotlib

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
np, pd, plt

(<module 'numpy' from 'C:\\Users\\hthog\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>,
 <module 'pandas' from 'C:\\Users\\hthog\\anaconda3\\lib\\site-packages\\pandas\\__init__.py'>,
 <module 'matplotlib.pyplot' from 'C:\\Users\\hthog\\anaconda3\\lib\\site-packages\\matplotlib\\pyplot.py'>)

In [5]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__pac

In [10]:
# float32 vs float64
x = np.float32(2 ** 127)
x, type(x)

(1.7014118e+38, numpy.float32)

In [11]:
x = np.float32(2 ** 128)
x, type(x)

C:\Users\hthog\AppData\Local\Temp\ipykernel_24152\2967301145.py:1: RuntimeWarning: overflow encountered in cast
  x = np.float32(2 ** 128)


(inf, numpy.float32)

In [12]:
x = np.float64(2 ** 128)
x, type(x)

(3.402823669209385e+38, numpy.float64)

In [13]:
# arrays
array = np.array([5,4,3,2,1])
print(array)
print(array.dtype)

[5 4 3 2 1]
int32


In [14]:
range_array = np.arange(0,101)
range_array

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

## Two-dimensional lists and arrays

In [18]:
list_of_lists = [[4,5,6],[1,2,3],[7,8,9]]
list_of_lists

[[4, 5, 6], [1, 2, 3], [7, 8, 9]]

In [20]:
two_dim = np.array(list_of_lists)
two_dim

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [21]:
two_dim[0], two_dim[0][1]

(array([4, 5, 6]), 5)

In [27]:
for i in range(len(two_dim)):
    row = two_dim[i]
    for j in range(len(row)):
        print("i, j: ", i, j)
        print("val: ", row[j])

i, j:  0 0
val:  4
i, j:  0 1
val:  5
i, j:  0 2
val:  6
i, j:  1 0
val:  1
i, j:  1 1
val:  2
i, j:  1 2
val:  3
i, j:  2 0
val:  7
i, j:  2 1
val:  8
i, j:  2 2
val:  9


In [29]:
for row in two_dim:
    print(row)
    for item in row:
        print(item)

[4 5 6]
4
5
6
[1 2 3]
1
2
3
[7 8 9]
7
8
9


## Zeros, Empty, Ones, and Likes

In [30]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
np.empty((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
np.zeros_like(list_of_lists)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## log values

In [34]:
np.log(1)

0.0

In [35]:
np.log(np.e)

1.0

In [36]:
np.log(two_dim)

array([[1.38629436, 1.60943791, 1.79175947],
       [0.        , 0.69314718, 1.09861229],
       [1.94591015, 2.07944154, 2.19722458]])

In [37]:
print((np.log(5)/np.log(2)))
print((np.log10(5)/np.log10(2)))

2.321928094887362
2.3219280948873626


In [38]:
np.pi, np.inf, np.nan

(3.141592653589793, inf, nan)